export {default as Hero} from './Hero'
export {default as About} from './About'
export {default as Brands} from './Brands'
export {default as Career} from './Career'
export {default as Contact} from './Contact'
export {default as HugManagement} from './HugManagement'
export {default as Subsidiaries} from './Subsidiaries'